# Tutortunnin taulukko
 - Tee taulukko alla olevan mukaisesti

 11 12  13  14  15
 16 17  18  19  20
 21 22  23  24  25
 26 27  28  29  30
 31 32  33  34  
 
 - tee tauluun seuraavat haut
  - joka toinen arvo joka toiselta riviltä (11,13,15, 21,23,25, 31, 33, 35)
  - toisen ja neljännen rivin ensimmäiset arvot (16, 26)
  - toisen sarakkeen kaikki arvot (12,17,22,27,32)
  - ensimmäisen rivin toinen ja neljäs arvo (12,14)

In [83]:
import numpy as np

# myös näin
#a = np.arange(11,36,1).reshape((5,5))
a = np.arange(11,36,1)
a = np.reshape(a, (5,5))
print(a)



#Slice valitaan joka toinen joka toiselta riviltä
print(a[::2,::2])
b = a[::2,::2]

#Joka toinen toisesta sarakkeesta
print(a[1::2,0])
c = a[1::2,0]
#toinen sarake
print(a[:,1])
d = a[:,1]

# ensimmäisen rivin toinen ja neljäs arvo
print(a[0,1::2])
e = a[0,1::2]

print


[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
[[11 13 15]
 [21 23 25]
 [31 33 35]]
[16 26]
[12 17 22 27 32]
[12 14]
<class 'numpy.ndarray'>
