# Aloitus

In [2]:
print("Trying to import numpy")
try:
    import numpy
    importnumpy=True
except ImportError:
    importnumpy=False
try:
    import matplotlib
    importmatplot=True
except ImportError:
    importmatplot=False


print("Trying to import pytest")
try:
    import pytest
    importpytest=True
except ImportError:
    importpytest=False

if (importpytest == True) :
    print("Pytest is imported.")
else:
    print("Pytest import failed.")
if (importnumpy == True) :
    print("Numpy is imported.")
else:
    print("Numpy import failed.")

if (importmatplot == True) :
    print("Matplotlib is imported")
else:
    print("Matplotlib import failed")

Trying to import numpy
Trying to import pytest
Pytest is imported.
Numpy is imported.
Matplotlib is imported


## Tests complete

In [9]:
try:
    import numpy
except ImportError:
    print("Failed")

print("Hello World!")

Hello World!


In [7]:
muuttuja=2
muuttujab=2.7382
print(f"Muuttuja on {muuttuja:0>4b} jatketaan tekstiä")
print(f"Muuttuja B on {muuttujab:.2F} ja vielä jatketaan tekstiä")

Muuttuja on 0010 jatketaan tekstiä
Muuttuja B on 2.74 ja vielä jatketaan tekstiä


# Coursera tehtäviä

In [20]:
print(type(1.2))
print(type(8))
print(type('1'))

Val = False

if Val == True :
    print(True)
    print(type(True))
else:
    print(False)
    print(type(False))

print("done")

type("Hello" == "Word")

if "Hello" == "Word" :
    print("The same")
else:
    print("Not the same")

<class 'float'>
<class 'int'>
<class 'str'>
False
<class 'bool'>
done
Not the same


In [31]:
print(25/6)

luku1 = 25
luku2 = 6

print(luku1/luku2)
luku3 = luku1

luku1 = 22

print(luku1)
print(luku3)


luku1 /60

11/2

x = 4
x = x/2

print(x)

y=2*x**2-3
print(y)

4.166666666666667
4.166666666666667
22
25
2.0
5.0


In [44]:
name="Testi"

for i in range(len(name)):
    print(F"location, name: {i}, {name[i]}")

print(name.upper())
name.find("ti")


name = "John"
age = 30
print(f"My name is {name} and I am {age} years old.")


regular_string = "C:\new_folder\file.txt"
print("Regular String:", regular_string)

raw_string = r"C:\new_folder\file.txt"
print("Raw String:", raw_string)


location, name: 0, T
location, name: 1, e
location, name: 2, s
location, name: 3, t
location, name: 4, i
TESTI
My name is John and I am 30 years old.
Regular String: C:
ew_folderile.txt
Raw String: C:\new_folder\file.txt


In [72]:
import re
g = "Mary had a little lamb Little lamb, little lamb Mary had a little lamb \
Its fleece was white as snow And everywhere that Mary went Mary went, Mary went \
Everywhere that Mary went The lamb was sure to go"

print(g.find("snow"))
print(g.replace("Mary", "Bob"))
print(g.replace(",","."))

a=g.split()
print(a)
print()
print()
print(g.upper())
print(g.lower())
print()
print()
s3 = "House number- 1105"

result = re.search(r'\d', s3)

if result:
    print("Digit found")
else:
    print("Digit not found.")

str1= "The quick brown fox jumps over the lazy dog."
print()
print(str1)
new_str1 = re.sub(r"fox", "bear", str1)
print()
print(new_str1)

print()

str2 = "how much wood would a woodchuch chuck, if a woodchuck could chuck wood?"

matches = re.findall(r"woo", str2)
print(matches)
print(f"There is {len(matches)} matches on the string for woo")

print("AB\nC\nDE")

print("4%3: ", 4%3)


95
Bob had a little lamb Little lamb, little lamb Bob had a little lamb Its fleece was white as snow And everywhere that Bob went Bob went, Bob went Everywhere that Bob went The lamb was sure to go
Mary had a little lamb Little lamb. little lamb Mary had a little lamb Its fleece was white as snow And everywhere that Mary went Mary went. Mary went Everywhere that Mary went The lamb was sure to go
['Mary', 'had', 'a', 'little', 'lamb', 'Little', 'lamb,', 'little', 'lamb', 'Mary', 'had', 'a', 'little', 'lamb', 'Its', 'fleece', 'was', 'white', 'as', 'snow', 'And', 'everywhere', 'that', 'Mary', 'went', 'Mary', 'went,', 'Mary', 'went', 'Everywhere', 'that', 'Mary', 'went', 'The', 'lamb', 'was', 'sure', 'to', 'go']


MARY HAD A LITTLE LAMB LITTLE LAMB, LITTLE LAMB MARY HAD A LITTLE LAMB ITS FLEECE WAS WHITE AS SNOW AND EVERYWHERE THAT MARY WENT MARY WENT, MARY WENT EVERYWHERE THAT MARY WENT THE LAMB WAS SURE TO GO
mary had a little lamb little lamb, little lamb mary had a little lamb its flee

Regular expressions (RegEx) are patterns used to match and manipulate strings of text. There are several special sequences in RegEx that can be used to match specific characters or patterns.

| Special Sequence | Meaning                 | 	Example             |
| -----------  | ----------------------- | ----------------------|
| \d|Matches any digit character (0-9)|"123" matches "\d\d\d"|
|\D|Matches any non-digit character|"hello" matches "\D\D\D\D\D"|
|\w|Matches any word character (a-z, A-Z, 0-9, and _)|"hello_world" matches "\w\w\w\w\w\w\w\w\w\w\w"|
|\W|Matches any non-word character|	"@#$%" matches "\W\W\W\W"|
|\s|Matches any whitespace character (space, tab, newline, etc.)|"hello world" matches "\w\w\w\w\w\s\w\w\w\w\w"|
|\S|Matches any non-whitespace character|"hello_world" matches "\S\S\S\S\S\S\S\S\S"|
|\b|Matches the boundary between a word character and a non-word character|"cat" matches "\bcat\b" in "The cat sat on the mat"|
|\B|Matches any position that is not a word boundary|"cat" matches "\Bcat\B" in "category" but not in "The cat sat on the mat"|


# Koe

In [77]:
1+3*2
'1'+ '2'
'hello'.upper()

str(1+1)

x = 2/2
type(x)

float

# Lists and tuples

In [102]:
tuple1 = ("disco", 10, 1.2, "hard rock", 10)

print(tuple1[0])

# Tuples
Ratings = (10,9,5,4,10)

print(Ratings)

tuple2 = [(1,2,3,4,5), Ratings]

print(tuple2)

print(tuple1[0:2])
print(tuple1[3:5])

RatingsSorted = sorted(Ratings)

print(RatingsSorted)

NT = (1,2,("pop","rock"), (3,4), ("disco"), (1,2))

print(NT[2][0])
print(NT[2][1])
print(NT[3][0])
print(NT[3][1])
print(NT[4][0])
print(NT[5][0])
print(NT)


print()
print()
print("Lists are immutable")
L = ["Michale jackson", 10.1,1982]

print(L)

print(L[-1])

L[3:5]:["MJ", 1]
print(L)
L.extend(["Pop", 10])

L.append(["pop", 10])

print(L)

L[0] = "Hard rock"

print(L)

L[0].split(" ")

print(L)
B = L[:]

print(L)
print(B)

B[0] = "Michael Jackson"

print(L)
print(B)

L=["Michael Jackson", 10.1, 1982, [1, 2], ("A", 1)]
print()
print(L)
print()
print('the same element using negative and positive indexing:\n Postive:',L[0],
'\n Negative:' , L[-3]  )
print('the same element using negative and positive indexing:\n Postive:',L[1],
'\n Negative:' , L[-2]  )
print('the same element using negative and positive indexing:\n Postive:',L[2],
'\n Negative:' , L[-1]  )



disco
(10, 9, 5, 4, 10)
[(1, 2, 3, 4, 5), (10, 9, 5, 4, 10)]
('disco', 10)
('hard rock', 10)
[4, 5, 9, 10, 10]
pop
rock
3
4
d
1
(1, 2, ('pop', 'rock'), (3, 4), 'disco', (1, 2))


Lists are immutable
['Michale jackson', 10.1, 1982]
1982
['Michale jackson', 10.1, 1982]
['Michale jackson', 10.1, 1982, 'Pop', 10, ['pop', 10]]
['Hard rock', 10.1, 1982, 'Pop', 10, ['pop', 10]]
['Hard rock', 10.1, 1982, 'Pop', 10, ['pop', 10]]
['Hard rock', 10.1, 1982, 'Pop', 10, ['pop', 10]]
['Hard rock', 10.1, 1982, 'Pop', 10, ['pop', 10]]
['Hard rock', 10.1, 1982, 'Pop', 10, ['pop', 10]]
['Michael Jackson', 10.1, 1982, 'Pop', 10, ['pop', 10]]

['Michael Jackson', 10.1, 1982, [1, 2], ('A', 1)]

the same element using negative and positive indexing:
 Postive: Michael Jackson 
 Negative: 1982
the same element using negative and positive indexing:
 Postive: 10.1 
 Negative: [1, 2]
the same element using negative and positive indexing:
 Postive: 1982 
 Negative: ('A', 1)


In [124]:
#Lists
a_list = [1, "hello", [1,2,3], True]

print(a_list)

print()
print(a_list[1])
print(a_list[1:3])

#concatenate

A = [1, 'a']
B = [2,1, 'd']

print(A)
print(B)

C=A+B

#A.extend(B)
print("concatenated to C: ", C)


s_list = []
print(s_list)
s_list = ["Watch", "Laptop", "Shoes", "Pen", "Clothes"]
print(s_list)
s_list.append("Football")
print(s_list)
print(s_list[0])
print(s_list[-1])

print()
print(s_list)
print(s_list[1:3])

s_list[3] = "Notebook"

print(s_list)
del(s_list[-2])

print(s_list)





[1, 'hello', [1, 2, 3], True]

hello
['hello', [1, 2, 3]]
[1, 'a']
[2, 1, 'd']
concatenated to C:  [1, 'a', 2, 1, 'd']
[]
['Watch', 'Laptop', 'Shoes', 'Pen', 'Clothes']
['Watch', 'Laptop', 'Shoes', 'Pen', 'Clothes', 'Football']
Watch
Football

['Watch', 'Laptop', 'Shoes', 'Pen', 'Clothes', 'Football']
['Laptop', 'Shoes']
['Watch', 'Laptop', 'Shoes', 'Notebook', 'Clothes', 'Football']
['Watch', 'Laptop', 'Shoes', 'Notebook', 'Football']


In [146]:
#Tuples
tuple1 = ("disco",10,1.2 )
tuple1

type(tuple1)

print(tuple1[0])
print(tuple1[1])
print(tuple1[2])

print(type(tuple1[0]))
print(type(tuple1[1]))
print(type(tuple1[2]))
print(tuple1[-1])
print(tuple1[-2])
print(tuple1[-3])


print()
tuple2 = tuple1 + ("hard rock", 10)
tuple2

tuple2[0:3]
tuple2[3:5]
len(tuple2)


Ratings = (0, 9, 6, 5, 10, 8, 9, 6, 2)
RatingsSorted = sorted(Ratings)
RatingsSorted

NestedT =(1, 2, ("pop", "rock") ,(3,4),("disco",(1,2)))
"""
print(NestedT)

print("Element 0 of Tuple: ", NestedT[0])
print("Element 1 of Tuple: ", NestedT[1])
print("Element 2 of Tuple: ", NestedT[2])
print("Element 3 of Tuple: ", NestedT[3])
print("Element 4 of Tuple: ", NestedT[4])

# Print element on each index, including nest indexes
print("Element 2, 0 of Tuple: ",   NestedT[2][0])
print("Element 2, 1 of Tuple: ",   NestedT[2][1])
print("Element 3, 0 of Tuple: ",   NestedT[3][0])
print("Element 3, 1 of Tuple: ",   NestedT[3][1])
print("Element 4, 0 of Tuple: ",   NestedT[4][0])
print("Element 4, 1 of Tuple: ",   NestedT[4][1])
"""
# Excersizes


genres_tuple = ("pop", "rock", "soul", "hard rock", "soft rock", \
                "R&B", "progressive rock", "disco") 
genres_tuple
print("Excersizes")
print()
print(len(genres_tuple))
print(genres_tuple[3])
print(genres_tuple[3:6])

print(genres_tuple[0:2])

print(genres_tuple.index("disco"))


C_tuple = (-5,1,-3)
C_list = sorted(C_tuple)
print(C_list)


disco
10
1.2
<class 'str'>
<class 'int'>
<class 'float'>
1.2
10
disco

Excersizes

8
hard rock
('hard rock', 'soft rock', 'R&B')
('pop', 'rock')
7
[-5, -3, 1]


# Cheatsheet

In [ ]:
list_name.append(element) 

fruits = ["apple", "banana", "orange"] 
fruits.append("mango") print(fruits)

my_list = [1, 2, 3, 4, 5] 
new_list = my_list.copy() print(new_list) 
# Output: [1, 2, 3, 4, 5]

my_list = [1, 2, 2, 3, 4, 2, 5, 2] 
count = my_list.count(2) print(count) 
# Output: 4

fruits = ["apple", "banana", "orange", "mango"]

my_list = [10, 20, 30, 40, 50] 
del my_list[2] # Removes the element at index 2 print(my_list) 
# Output: [10, 20, 40, 50]


fruits = ["apple", "banana", "orange"] 
more_fruits = ["mango", "grape"] 
fruits.extend(more_fruits) 
print(fruits)

my_list = [10, 20, 30, 40, 50] 
print(my_list[0]) 
# Output: 10 (accessing the first element) 
print(my_list[-1]) 
# Output: 50 (accessing the last element using negative indexing)

my_list = [1, 2, 3, 4, 5] 
my_list.insert(2, 6) 
print(my_list)

my_list = [10, 20, 30, 40, 50] 
my_list[1] = 25 # Modifying the second element 
print(my_list) 
# Output: [10, 25, 30, 40, 50]

my_list = [10, 20, 30, 40, 50] 
removed_element = my_list.pop(2) # Removes and returns the element at index 2 
print(removed_element) 
# Output: 30 

print(my_list) 
# Output: [10, 20, 40, 50] 

my_list = [10, 20, 30, 40, 50] 
removed_element = my_list.pop(2) # Removes and returns the element at index 2 
print(removed_element) 
# Output: 30 

print(my_list) 
# Output: [10, 20, 40, 50] 

my_list = [10, 20, 30, 40, 50] 
removed_element = my_list.pop() # Removes and returns the last element 
print(removed_element) 
# Output: 50 

print(my_list) 
# Output: [10, 20, 30, 40]

my_list = [10, 20, 30, 40, 50] 
my_list.remove(30) # Removes the element 30 
print(my_list) 
# Output: [10, 20, 40, 50]

my_list = [1, 2, 3, 4, 5] 
my_list.reverse() print(my_list) 
# Output: [5, 4, 3, 2, 1]

#list_name[start:end:step] 
my_list = [1, 2, 3, 4, 5] 
print(my_list[1:4]) 
# Output: [2, 3, 4] (elements from index 1 to 3)

print(my_list[:3]) 
# Output: [1, 2, 3] (elements from the beginning up to index 2) 

print(my_list[2:]) 
# Output: [3, 4, 5] (elements from index 2 to the end) 

print(my_list[::2]) 
# Output: [1, 3, 5] (every second element)

my_list = [5, 2, 8, 1, 9] 
my_list.sort() 
print(my_list) 
# Output: [1, 2, 5, 8, 9] 


my_list = [5, 2, 8, 1, 9] 
my_list.sort(reverse=True) 
print(my_list) 
# Output: [9, 8, 5, 2, 1]


# Dictionary

In [201]:
"""
person = dict({ "Name": "Michael" })
person = dict(2: {"age" = 21})

person["Country"] = "USA" # A new entry will be created. 
person["city"] = "Chicago" # Update the existing value for the same key

print(person)

person.clear()
print(person)
"""

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(type(thisdict))
person = {}
p1 = {
    "name":"John",
    "age":36,
    "country":"Norway"}
print(thisdict)
p2 = {
    "name":"Michael",
    "age":32,
    "country":"Valhalla"}

person.update({"person1" : p1, "person2" : p2})

print(person)

print(person.keys(), "\n")
print(person.values(), "\n")

for x in person.keys():
    print("\n", x, ":\n")
    for y in person[x]:
       #print(y["name"])
       #print(y["age"])
       #print(y["country"])
       print("\t", y, ":",person[x][y])



print("\n", person)





<class 'dict'>
{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}
{'person1': {'name': 'John', 'age': 36, 'country': 'Norway'}, 'person2': {'name': 'Michael', 'age': 32, 'country': 'Valhalla'}}
dict_keys(['person1', 'person2']) 

dict_values([{'name': 'John', 'age': 36, 'country': 'Norway'}, {'name': 'Michael', 'age': 32, 'country': 'Valhalla'}]) 


 person1 :

	 name : John
	 age : 36
	 country : Norway

 person2 :

	 name : Michael
	 age : 32
	 country : Valhalla

 {'person1': {'name': 'John', 'age': 36, 'country': 'Norway'}, 'person2': {'name': 'Michael', 'age': 32, 'country': 'Valhalla'}}


In [123]:
# Matmul Testausta


import numpy as np


def test(values, weights, bias):
    print("\nWelcome to test function!\n\n")
    #print(values.shape)
    #print(weights.shape)
    #print(bias.shape)
    
    result = [[0 for _ in range(len(weights[0]))] for _ in range(len(values))]
    
    # Required to make 3 different for loops to combine two matrices. First one iterates throught the rows of values
    # The second iterates through the columns of weights and the third iterates through the rows of weights.
    # These allow for all the row of weights to multiply the values from value and add the values together to results 
    # matrix
    for i in range(len(values)):
        for j in range(len(weights[0])):
            for k in range(len(weights)):
                #print(values[i][k], weights[k][j])
                result[i][j] += values[i][k] * weights[k][j]

    # After getting results from multiplication, add the bias value to the new matrix
    result = np.reshape(result,(3,5))
    
    for i in range(len(result)):
        for k in range(len(bias)):
            result[i][k] = result[i][k] + bias[k]

    # will zero negative values if needed.
    #result = np.maximum(0,result)

    return result

# Example shapes
input_data = np.array([(-0.127,0.223,-0.32),(-0.213,0.80,0.32), (0.213,-0.80,0.32)])  # Input vector
weights = np.random.rand(3, 5)       # Weight matrix (e.g., 3 inputs to 5 neurons)
bias = np.random.rand(5)             # Bias vector (one for each neuron in the dense layer)

# Dense layer computation using matmul

print(f"Input data:\n {input_data}\nweights:\n {weights}\nBias:\n {bias}\n")

z = np.matmul(input_data, weights) + bias

print(f"\n\nThe MATMUL result: {z}")

#output = np.maximum(0, z)  # ReLU activation

#print(f"\nThe MATMUL result is: {output}")

print(f"MyFunction test result: {test(input_data, weights,bias)}")

Input data:
 [[-0.127  0.223 -0.32 ]
 [-0.213  0.8    0.32 ]
 [ 0.213 -0.8    0.32 ]]
weights:
 [[0.61148212 0.6130108  0.23808731 0.01084467 0.04875576]
 [0.32647196 0.44853278 0.80539597 0.1786822  0.8469705 ]
 [0.80640026 0.64156509 0.65486027 0.82655421 0.03853089]]
Bias:
 [0.91333191 0.08227149 0.5497184  0.29734223 0.28943487]



The MATMUL result: [[ 0.65042885 -0.1008589   0.48952932  0.07131374  0.45978742]
 [ 1.30231187  0.51582725  1.35287786  0.70247543  0.96895618]
 [ 1.04044812  0.0593174   0.16566951  0.42120373 -0.36542667]]

Welcome to test function!


MyFunction test result: [[ 0.65042885 -0.1008589   0.48952932  0.07131374  0.45978742]
 [ 1.30231187  0.51582725  1.35287786  0.70247543  0.96895618]
 [ 1.04044812  0.0593174   0.16566951  0.42120373 -0.36542667]]
